version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
  catalogdb:
    image: postgres:15
  basketdb:
    image: postgres:15
  distributedcache:
    image: redis
  orderdb:
    image: mcr.microsoft.com/mssql/server
  messagebroker:
    image: rabbitmq:management
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
        context: .
        dockerfile: Services/Catalog/Catalog.API/Dockerfile
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
        context: .
        dockerfile: Services/Basket/Basket.API/Dockerfile
  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
        context: .
        dockerfile: Services/Discount/Discount.Grpc/Dockerfile
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    # IMPORTANT: Ensure there is NO 'build' section here.

volumes:
  # This declares the volume so the override file can use it
  postgres_catalog:
  postgres_basket:
    